org: avtrain
app: graphql-apis
service: av-clientresourcesapi

frameworkVersion: "3"

package:
  individually: true
  patterns:
    - '!layers/**'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 180
  region: ${opt:region, 'eu-west-2'}
  stage: ${opt:stage, 'dev'}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource:
            - "arn:aws:secretsmanager:${self:provider.region}:${param:account}:secret:*"

  environment:
    STAGE: ${param:stage}
    ACCOUNT_ID: ${param:account}
    REGION: ${param:region}
    DB_HOST: ${param:DB_HOST}
    DB_SECRETS: ${param:DB_SECRETS}
    DATABASE: ${param:DATABASE}
    USER_POOL_ID: ${param:userPoolId}

  vpc:
    securityGroupIds:
      - ${param:sgId}
    subnetIds:
      - ${param:subnetId}

  layers:
    - { Ref: AvClientResourceCommonLibsLambdaLayer }

plugins:
  - serverless-appsync-plugin
  - serverless-offline

custom:
  genericRequestTemplate: mapping-templates/generic.request.vtl
  genericResponseTemplate: mapping-templates/generic.response.vtl

appSync:
  name: ${self:service}-${self:provider.stage}
  domain:
    name: ${param:domainName}
    certificateArn: ${param:certificateARN}

  authentication:
    type: "AMAZON_COGNITO_USER_POOLS"
    config:
      userPoolId: ${param:userPoolId}

  resolvers:
    Query.getAircraftByClientId:
      dataSource: queryAircraftLambda
      request: ${self:custom.genericRequestTemplate}
      response: ${self:custom.genericResponseTemplate}
      kind: UNIT
    Mutation.createAircraft:
      dataSource: mutationAircraftLambda
      request: ${self:custom.genericRequestTemplate}
      response: ${self:custom.genericResponseTemplate}
      kind: UNIT
    Mutation.updateAircraft:
      dataSource: mutationAircraftLambda
      request: ${self:custom.genericRequestTemplate}
      response: ${self:custom.genericResponseTemplate}
      kind: UNIT
    Mutation.updateAircraftStatus:
      dataSource: mutationAircraftLambda
      request: ${self:custom.genericRequestTemplate}
      response: ${self:custom.genericResponseTemplate}
      kind: UNIT

  dataSources:
    queryAircraftLambda:
      type: AWS_LAMBDA
      description: "Get Operations DataSource"
      timeout: 30
      config:
        functionArn: "arn:aws:lambda:${self:provider.region}:${param:account}:function:${self:service}-${self:provider.stage}-queryAircraftHandler"
        serviceRoleArn:
          Fn::GetAtt:
            - avClientResourceServiceRole
            - Arn
    mutationAircraftLambda:
      type: AWS_LAMBDA
      description: "Get Operations DataSource"
      timeout: 30
      config:
        functionArn: "arn:aws:lambda:${self:provider.region}:${param:account}:function:${self:service}-${self:provider.stage}-mutationAircraftHandler"
        serviceRoleArn:
          Fn::GetAtt:
            - avClientResourceServiceRole
            - Arn

functions:
  queryAircraftHandler:
    handler: src/queryAircraftHandler.handler
  mutationAircraftHandler:
    handler: src/mutationAircraftHandler.handler

layers:
  avClientResourceCommonLibs:
    path: layers
    compatibleRuntimes:
      - nodejs18.x

resources:
  Resources:
    avClientResourceServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: avClientResourceServiceRole-${self:provider.stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: avClientResourceServiceRole-Policy-${self:provider.stage}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:invokeFunction
                  Resource:
                    - "arn:aws:lambda:${self:provider.region}:${param:account}:function:${self:service}-${self:provider.stage}-*"
